"""ajustando visyon para multiempresa2

Revision ID: 0ec30844203f
Revises: d391329f1dd7
Create Date: 2026-01-09 20:00:15.343537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec30844203f'
down_revision = 'd391329f1dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerta_inatividade_cliente', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('financeiro_titulo', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('financeiro_titulo', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('alerta_inatividade_cliente', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
