"""add contato

Revision ID: 22b04479e9da
Revises: be1169bbb10d
Create Date: 2026-01-15 10:23:32.567108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b04479e9da'
down_revision = 'be1169bbb10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_column('contato')

    # ### end Alembic commands ###
