"""ADD REDE DE LOJA

Revision ID: 3776eeaed0b4
Revises: d1d98a3e59de
Create Date: 2026-01-13 23:35:05.214668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3776eeaed0b4'
down_revision = 'd1d98a3e59de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rede_loja', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_nota_fiscal_rede_loja'), ['rede_loja'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_rede_loja'))
        batch_op.drop_column('rede_loja')

    # ### end Alembic commands ###
