"""AJUSTE empresa id - colaborador

Revision ID: 3ba5f8057540
Revises: 7535a8c3789f
Create Date: 2026-01-19 14:26:57.110784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba5f8057540'
down_revision = '7535a8c3789f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_colaborador_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_colaborador_empresa_id'))
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
