"""ajutes para visyonx3

Revision ID: 459d1d729a2f
Revises: acd157aa1b3c
Create Date: 2026-01-05 23:20:08.975022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459d1d729a2f'
down_revision = 'acd157aa1b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tela')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tela',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendida', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('tela_empresa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tela_pkey'))
    )
    # ### end Alembic commands ###
