"""AJUSTE NO EMAIL DA EMPRESA

Revision ID: 7535a8c3789f
Revises: 7e617b96e00f
Create Date: 2026-01-19 13:44:39.717721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7535a8c3789f'
down_revision = '7e617b96e00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_nf_empresa_data_numero'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_pedido'))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nota_fiscal_pedido'), ['pedido'], unique=False)
        batch_op.create_index(batch_op.f('idx_nf_empresa_data_numero'), ['empresa_id', sa.literal_column('data_emissao DESC'), sa.literal_column('numero DESC')], unique=False)

    # ### end Alembic commands ###
