"""add codigo do cliente em nf

Revision ID: 89f41720b5a2
Revises: 3ba5f8057540
Create Date: 2026-01-19 15:57:55.180802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f41720b5a2'
down_revision = '3ba5f8057540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_cliente', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_nota_fiscal_codigo_cliente'), ['codigo_cliente'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_codigo_cliente'))
        batch_op.drop_column('codigo_cliente')

    # ### end Alembic commands ###
