"""ADD NOTA FISCAL

Revision ID: a28a0bd9a8c8
Revises: ab3e6d5ebc33
Create Date: 2026-01-13 18:23:11.505613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28a0bd9a8c8'
down_revision = 'ab3e6d5ebc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('cfop', sa.String(length=10), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('representante', sa.String(length=100), nullable=True),
    sa.Column('pedido', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_faturado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_transporte', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero', 'serie', name='uq_nf_empresa_numero_serie')
    )
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nota_fiscal_cfop'), ['cfop'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_data_emissao'), ['data_emissao'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_pedido'), ['pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_representante'), ['representante'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_serie'), ['serie'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_serie'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_representante'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_pedido'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_numero'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_data_emissao'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_cliente'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_cfop'))

    op.drop_table('nota_fiscal')
    # ### end Alembic commands ###
