"""add email na empresa

Revision ID: ab3e6d5ebc33
Revises: 0ec30844203f
Create Date: 2026-01-11 20:06:11.067053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab3e6d5ebc33'
down_revision = '0ec30844203f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ref_venda_codigo'))
        batch_op.drop_index(batch_op.f('ix_ref_venda_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_ref_venda_linha'))
        batch_op.drop_index(batch_op.f('ix_ref_venda_referencia'))

    op.drop_table('ref_venda')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('email')

    op.create_table('ref_venda',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referencia', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('linha', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('combinacao', sa.VARCHAR(length=240), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('ref_venda_empresa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ref_venda_pkey'))
    )
    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ref_venda_referencia'), ['referencia'], unique=True)
        batch_op.create_index(batch_op.f('ix_ref_venda_linha'), ['linha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ref_venda_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ref_venda_codigo'), ['codigo'], unique=False)

    # ### end Alembic commands ###
