"""ajutes para visyonx2

Revision ID: acd157aa1b3c
Revises: 5988946c8ebe
Create Date: 2026-01-05 23:17:31.412043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acd157aa1b3c'
down_revision = '5988946c8ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_streaming')
    op.drop_table('conta')
    op.drop_table('tela')
    op.drop_table('servico')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('servico_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('imagem', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('telas_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_venda_padrao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('comissao_padrao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name='servico_empresa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='servico_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tela',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tela_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendida', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name='tela_conta_id_fkey'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name='tela_empresa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tela_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('conta',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conta_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('servico_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_venda_override', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('comissao_override', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_investido', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name='conta_empresa_id_fkey'),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], name='conta_servico_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='conta_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('venda_streaming',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('servico_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tela_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_venda', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('valor_comissao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_venda', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_entrega', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('venda_streaming_empresa_id_fkey')),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], name=op.f('venda_streaming_servico_id_fkey')),
    sa.ForeignKeyConstraint(['tela_id'], ['tela.id'], name=op.f('venda_streaming_tela_id_fkey')),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], name=op.f('venda_streaming_vendedor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('venda_streaming_pkey'))
    )
    # ### end Alembic commands ###
