"""nome fantasia

Revision ID: be1169bbb10d
Revises: c7db055c8b70
Create Date: 2026-01-14 23:58:35.100594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1169bbb10d'
down_revision = 'c7db055c8b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaborador_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaborador_codigo'))

    op.drop_table('colaborador')
    # ### end Alembic commands ###
