"""aumentando caracter de modelo nf3

Revision ID: c7db055c8b70
Revises: 68a991816df0
Create Date: 2026-01-14 12:14:29.182954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7db055c8b70'
down_revision = '68a991816df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.alter_column('pedido',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.alter_column('pedido',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
