"""AJUSTE COD TRANSP

Revision ID: d1d98a3e59de
Revises: a28a0bd9a8c8
Create Date: 2026-01-13 22:06:53.532952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d98a3e59de'
down_revision = 'a28a0bd9a8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_transportadora', sa.String(length=20), nullable=True))
        batch_op.drop_column('valor_transporte')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_transporte', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('codigo_transportadora')

    # ### end Alembic commands ###
