"""ajustando visyon para multiempresa

Revision ID: d391329f1dd7
Revises: 459d1d729a2f
Create Date: 2026-01-09 19:50:50.075302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd391329f1dd7'
down_revision = '459d1d729a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerta_inatividade_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alerta_inatividade_cliente_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('financeiro_titulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('empresa_nome', sa.String(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_fin_titulo_emp_doc_emis_venc_valor'), type_='unique')
        batch_op.create_unique_constraint('uq_fin_titulo_emp_doc_emis_venc_valor', ['empresa_nome', 'numero_doc', 'emissao', 'vencimento', 'valor'])
        batch_op.create_index(batch_op.f('ix_financeiro_titulo_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('empresa')

    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ref_venda_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_venda_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_venda_empresa_id'))
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ref_venda_empresa_id'))
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('financeiro_titulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_financeiro_titulo_empresa_id'))
        batch_op.drop_constraint('uq_fin_titulo_emp_doc_emis_venc_valor', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_fin_titulo_emp_doc_emis_venc_valor'), ['empresa', 'numero_doc', 'emissao', 'vencimento', 'valor'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('empresa_nome')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('alerta_inatividade_cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerta_inatividade_cliente_empresa_id'))
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
