"""estrutura inicial completa

Revision ID: e591fd400ee0
Revises: 
Create Date: 2026-01-05 18:59:49.210798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e591fd400ee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerta_inatividade_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('ultima_data_venda', sa.Date(), nullable=False),
    sa.Column('data_alerta', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerta_inatividade_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerta_inatividade_cliente_cliente'), ['cliente'], unique=False)

    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('financeiro_titulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.Column('cliente', sa.String(length=180), nullable=True),
    sa.Column('representante', sa.String(length=120), nullable=True),
    sa.Column('especie', sa.String(length=80), nullable=True),
    sa.Column('numero_doc', sa.String(length=120), nullable=False),
    sa.Column('emissao', sa.Date(), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('liquidacao', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('conta_bancaria', sa.String(length=120), nullable=True),
    sa.Column('banco', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa', 'numero_doc', 'emissao', 'vencimento', 'valor', name='uq_fin_titulo_emp_doc_emis_venc_valor')
    )
    with op.batch_alter_table('financeiro_titulo', schema=None) as batch_op:
        batch_op.create_index('ix_fin_tit_cliente', ['cliente'], unique=False)
        batch_op.create_index('ix_fin_tit_representante', ['representante'], unique=False)
        batch_op.create_index('ix_fin_tit_vencimento', ['vencimento'], unique=False)

    op.create_table('ref_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=False),
    sa.Column('linha', sa.String(length=40), nullable=True),
    sa.Column('codigo', sa.String(length=120), nullable=True),
    sa.Column('combinacao', sa.String(length=240), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('media_pct', sa.Float(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ref_venda_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ref_venda_linha'), ['linha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ref_venda_referencia'), ['referencia'], unique=True)

    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representante', sa.String(length=150), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('pedido', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('data_inclusao', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('produto', sa.String(length=150), nullable=True),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('regiao', sa.String(length=100), nullable=True),
    sa.Column('rede_loja', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venda_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_venda_data_inclusao'), ['data_inclusao'], unique=False)
        batch_op.create_index(batch_op.f('ix_venda_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_venda_pedido'), ['pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_venda_representante'), ['representante'], unique=False)

    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenca_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('dias_acesso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('telas_total', sa.Integer(), nullable=True),
    sa.Column('valor_venda_padrao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comissao_padrao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('is_admin_empresa', sa.Boolean(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=120), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('valor_venda_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissao_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_investido', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_acao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nome', sa.String(length=100), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'usuario_id', 'categoria', 'acao', name='unique_permissao_usuario_empresa')
    )
    op.create_table('tela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('vendida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda_streaming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('tela_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.ForeignKeyConstraint(['tela_id'], ['tela.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_streaming')
    op.drop_table('tela')
    op.drop_table('permissao')
    op.drop_table('log_acao')
    op.drop_table('conta')
    op.drop_table('usuario')
    op.drop_table('servico')
    op.drop_table('licenca_sistema')
    op.drop_table('cliente')
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venda_representante'))
        batch_op.drop_index(batch_op.f('ix_venda_pedido'))
        batch_op.drop_index(batch_op.f('ix_venda_estado'))
        batch_op.drop_index(batch_op.f('ix_venda_data_inclusao'))
        batch_op.drop_index(batch_op.f('ix_venda_cliente'))

    op.drop_table('venda')
    with op.batch_alter_table('ref_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ref_venda_referencia'))
        batch_op.drop_index(batch_op.f('ix_ref_venda_linha'))
        batch_op.drop_index(batch_op.f('ix_ref_venda_codigo'))

    op.drop_table('ref_venda')
    with op.batch_alter_table('financeiro_titulo', schema=None) as batch_op:
        batch_op.drop_index('ix_fin_tit_vencimento')
        batch_op.drop_index('ix_fin_tit_representante')
        batch_op.drop_index('ix_fin_tit_cliente')

    op.drop_table('financeiro_titulo')
    op.drop_table('empresa')
    with op.batch_alter_table('alerta_inatividade_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerta_inatividade_cliente_cliente'))

    op.drop_table('alerta_inatividade_cliente')
    # ### end Alembic commands ###
